- hosts: webserver
  tasks:
   - name: installing httpd package
     package: 
      name: "httpd"
      state: present



   - name: copying web pages
     template: 
      dest: "/var/www/html"
      src: "index.html"

   - name: starting the service
     service: 
      name: "httpd"
      state: started
      enabled: yes
